### PR TITLE
Replace '.contains must equal true' with 'must include' in tests

### PR DESCRIPTION
**Pull request by techncl**
Previously if a test ran and failed, it would just say 'true did not equal false' which is not helpful. This fix will show you the strings that it's comparing so it is easier to see what is incorrect

### CODE REVIEW

**Review by TomJKing — DISMISSED** [review]
Looks good. Thanks

**Review by TomJKing — DISMISSED** [review]
Looks good. Thanks

**Comment by techncl** [comment]
Waiting on [Vimlesh's PR](https://github.com/nationalarchives/tdr-transfer-frontend/pull/2448) to get merged before I merge this just because he's had to deal a lot of merge conflicts while writing his code

**Review by vimleshtna — APPROVED** [review]
Looks good.

**Pull request merged**
